import { useEffect, useMemo, useRef, useState } from 'react';
const MAX_EVENTS = 8000;
const STORAGE_KEY = 'cmvisual.worldTimeline.v2';
const MAX_PERSIST_BYTES = 4_000_000;
const finite = (v) => { const n = Number(v); return Number.isFinite(n) ? n : null; };
function observationPoint(d) { const px=finite(d?.position?.x), pz=finite(d?.position?.z); if(px!=null&&pz!=null)return {x:px,z:pz}; const r=finite(d?.distance), a=finite(d?.angle); if(r==null||a==null)return null; const rad=a*Math.PI/180; return {x:r*Math.cos(rad),z:r*Math.sin(rad)}; }
export default function useWorldTimeline({ observations=[], geo=null, sessionId=null, enabled=true }={}) {
  const eventsRef=useRef([]); const lastRef=useRef(0); const [, forceRender]=useState(0); const [cursor,setCursor]=useState(null);
  useEffect(()=>{ try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'); if(Array.isArray(saved)) eventsRef.current=saved.slice(-MAX_EVENTS); } catch {} },[]);
  useEffect(()=>{ if(!enabled)return; const now=Date.now(); if(now-lastRef.current<1000)return; lastRef.current=now; const batch=(Array.isArray(observations)?observations:[]).map(d=>{const t=finite(d?.measuredAt??d?.timestamp??d?.observedAt)??now; const position=observationPoint(d); const eventId=String(d?.eventId||`${sessionId||'local'}:${t}:${String(d?.trackId??d?.id??'unknown')}`); return {eventId,sessionId:d?.sessionId||sessionId||'local',observedAt:new Date(t).toISOString(),trackId:String(d?.trackId??d?.id??eventId),source:d?.source||'LOCAL INPUT',type:d?.type||'unknown',evidenceClass:String(d?.evidenceClass||d?.evidence_class||(d?.source?'MEASURED':'UNAVAILABLE')).toUpperCase(),position,distanceM:finite(d?.distance??(position?Math.hypot(position.x,position.z):null)),angleDeg:finite(d?.angle??(position?Math.atan2(position.z,position.x)*180/Math.PI:null)),moving:typeof d?.moving==='boolean'?d.moving:null,speedMps:finite(d?.derivedTrack?.speedMps??d?.speedMps??d?.speed),confidence:finite(d?.confidence),uncertaintyM:finite(d?.uncertaintyM),provenance:d?.provenance||null,geo:d?.geo|| (geo&&finite(geo.lat)!=null&&finite(geo.lon)!=null?{latitude:finite(geo.lat),longitude:finite(geo.lon),accuracyM:finite(geo.accuracy)}:null),federated:Boolean(d?.federated),coordinateFrame:d?.coordinateFrame||null,alignment:d?.alignment||null};}).filter(e=>e.trackId&&e.position); if(!batch.length)return; const seen=new Set(eventsRef.current.slice(-1000).map(e=>e.eventId)); batch.forEach(e=>{if(!seen.has(e.eventId))eventsRef.current.push(e);}); if(eventsRef.current.length>MAX_EVENTS)eventsRef.current.splice(0,eventsRef.current.length-MAX_EVENTS); try { const serialized=JSON.stringify(eventsRef.current); localStorage.setItem(STORAGE_KEY, serialized.length<=MAX_PERSIST_BYTES?serialized:JSON.stringify(eventsRef.current.slice(-Math.floor(MAX_EVENTS/2)))); } catch {} forceRender(v=>v+1); },[observations,geo,sessionId,enabled]);
  const events=eventsRef.current; const minTime=events.length?Date.parse(events[0].observedAt):null; const maxTime=events.length?Date.parse(events[events.length-1].observedAt):null; const active=cursor==null?maxTime:cursor;
  const visibleEvents=useMemo(()=>active?events.filter(e=>Date.parse(e.observedAt)<=active):[],[events,active]);
  const worldState=useMemo(()=>{const latestByTrack=new Map(); visibleEvents.forEach(e=>latestByTrack.set(e.trackId,e)); return {timestamp:active,tracks:[...latestByTrack.values()],eventCount:visibleEvents.length};},[visibleEvents,active]);
  const tracks=useMemo(()=>{const m=new Map();visibleEvents.forEach(e=>{if(!m.has(e.trackId))m.set(e.trackId,[]);m.get(e.trackId).push(e);});return [...m.entries()].map(([trackId,trail])=>({trackId,trail,latest:trail[trail.length-1]}));},[visibleEvents]);
  const timeline=useMemo(()=>({eventCount:events.length,visibleEventCount:visibleEvents.length,trackCount:tracks.length,minTime,maxTime,cursor:active,live:cursor==null}),[events.length,visibleEvents.length,tracks.length,minTime,maxTime,active,cursor]);
  return {events,tracks,worldState,timeline,cursor:active,setCursor,reset:()=>setCursor(null)};
}